name: CI
on: [push]
jobs:
  standard-checks:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install packages
        run: npm ci
      - name: Run Test Cases
        run: yarn ci:test
      - name: Bundle and Output
        run: yarn build